server:
  port: 8602

eureka:
  instance: trying-zuul-002
  prefer-ip-address: true      #false 表示使用主机名进行地址访问；true表示根据IP进行地址重定向
  client:
    serviceUrl:
      defaultZone: http://localhost:8802/eureka/
    register-with-eureka: false   #是否向服务中心注册 true是 false否
